// import bcrypt from 'bcryptjs';
const bcrypt = require('bcryptjs');

const data = {
  users: [
    {
      name: 'Sibusiso',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Lacoste Shoes',
      category: 'Shoes',
      image: '/images/pic1.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },

    {
      name: 'Product 2',
      category: 'Shoes',
      image: '/images/pic2.png',
      price: 650,
      brand: 'Nike',
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },

    {
      name: 'Product 3',
      category: 'Shoes',
      image: '/images/pic3.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Product 4',
      category: 'Shoes',
      image: '/images/pic4.png',
      price: 650,
      brand: 'Nike',
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Product 5',
      category: 'Shoes',
      image: '/images/pic5.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Product 6',
      category: 'Shoes',
      image: '/images/pic6.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Product 7',
      category: 'Shoes',
      image: '/images/pic7.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Product 8',
      category: 'Shoes',
      image: '/images/pic8.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
};

module.exports = data;
