const data = {
  products: [
    {
      _id: '1',
      name: 'Lacoste Shoes',
      category: 'Shoes',
      image: '/images/pic1.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '2',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic2.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '3',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic3.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic4.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic5.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic6.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic7.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Snuck Shoes',
      category: 'Shoes',
      image: '/images/pic8.png',
      price: 650,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
